[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200

# Denne linjen tvinger den til å bruke riktig versjon for C6
platform_packages =
    framework-arduinoespressif32 @ https://github.com

