[env:esp32-c6-devkitc-1]
platform = espressif32@12.3.2
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
# Vi fjerner den manuelle GitHub-linken og bruker den offisielle pakken
