name: PlatformIO Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Installer PlatformIO
        run: pip install --upgrade platformio
      - name: Tving nedlasting av C6-støtte
        run: |
          # Vi bruker wget (ikke git) for å laste ned pakken direkte
          wget https://github.com
          # Vi forteller PlatformIO at den skal bruke denne lokale fila
          pio platform install platform-espressif32.zip
      - name: Run PlatformIO Build
        run: pio run
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/**/firmware.bin
