name: PlatformIO Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sett opp Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer PlatformIO
        run: pip install --upgrade platformio

      - name: Run PlatformIO Build
        run: pio run
        env:
          PLATFORMIO_PLATFORM_ESPRESSIF32_URL: https://github.com
